version: "3.7"

services:
### PHP Container #########################################
  observerphp:
    container_name: observer-php
    hostname: observer-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html/app
    volumes:
      - ./:/var/www/html/app
    depends_on:
      - observerdb
      - observerredis


  ### NGINX Container #########################################
  nginx:
    container_name: observer-nginx
    image: nginx:1.17
    restart: unless-stopped
    depends_on:
      - observerphp
    ports:
      - 5000:80
    volumes:
      - ./:/var/www/html/app
      - ./docker/virtualhost.conf:/etc/nginx/conf.d/default.conf

### POSTGRESS Container #########################################
  observerdb:
    container_name: observer-db
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: observer
      POSTGRES_USER: observer-user
      POSTGRES_PASSWORD: secret
      PGPASSWORD: secret
    ports:
      - "54321:5432"

### Redis Container #########################################
  observerredis:
    container_name: observer-redis
    image: redis:5.0
    expose:
      - 6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
